server:
  port: 8083

fiap:
  api:
    path: '/agro-drones'

camel:
  springboot:
    name: ServiceRest

management:
  port: 8083

endpoints:
  enabled: false
  health:
    enabled: true

spring:
  rabbitmq:
    addresses: "copy url"
